### ISSUE TITLE
Error while running in the "diploid" mode

### ISSUE THREAD

**Issue by eshab5** [hringbauer/hapROH#15]
Hi Harald,

I am trying to run hapROH on a set of diploid samples so I have modified the script as following to show it is "diploid" and also changed "random_allele" = True to False.

```
iid = get_iid_from_i(meta_df, run_nr)

    hapsb_ind(iid=iid, chs=range(1,23), processes=6,
          path_targets= "./haproh_moderns",
          h5_path1000g='./1000g1240khdf5/all1240/chr',
          meta_path_ref='./1000g1240khdf5/all1240/meta_df_all.csv',
          folder_out='./Moderns', prefix_out='',
          e_model="diploid", p_model="Eigenstrat", n_ref=2504,
          random_allele=False, readcounts=False, delete=False, logfile=True, combine=True)
```

**However, I am getting error as the following:**

multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/apps/software/gcc-12.1.0/python/3.10.5/lib/python3.10/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/apps/software/gcc-12.1.0/python/3.10.5/lib/python3.10/multiprocessing/pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "/gpfs/data/raghavan-lab/bin/hapROH/package/hapsburg/PackagesSupport/hapsburg_run.py", line 74, in hapsb_chrom
    hmm.load_secondary_objects()
  File "/home/eshab5/.local/lib/python3.10/site-packages/hapsburg/hmm_inference.py", line 122, in load_secondary_objects
    self.load_emission_model(c, self.pCon)
  File "/home/eshab5/.local/lib/python3.10/site-packages/hapsburg/hmm_inference.py", line 158, in load_emission_model
    self.e_obj = load_emission_model(self.ref_states, e_model=self.e_model, c=c, pCon=pCon)
  File "/home/eshab5/.local/lib/python3.10/site-packages/hapsburg/emissions.py", line 363, in load_emission_model
    raise NotImplementedError("Emission Model not found!")
NotImplementedError: Emission Model not found!
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/ess/scratch/scratch1/eshab5//hapROH/run_hapROH.py", line 51, in <module>
    hapsb_ind(iid=iid, chs=range(1,23), processes=6,
  File "/gpfs/data/raghavan-lab/bin/hapROH/package/hapsburg/PackagesSupport/hapsburg_run.py", line 150, in hapsb_ind
    multi_run(hapsb_chrom, prms, processes = processes)
  File "/home/eshab5/.local/lib/python3.10/site-packages/hapsburg/PackagesSupport/parallel_runs/helper_functions.py", line 41, in multi_run
    results = pool.starmap(fun, prms)
  File "/apps/software/gcc-12.1.0/python/3.10.5/lib/python3.10/multiprocessing/pool.py", line 372, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "/apps/software/gcc-12.1.0/python/3.10.5/lib/python3.10/multiprocessing/pool.py", line 771, in get
    raise self._value
NotImplementedError: Emission Model not found!

**Comment by eshab5** [comment]
I have found the answer to my issue. Thank you.
